//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sieena.Parking.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sieena.Parking.Common.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has an active check in status..
        /// </summary>
        public static string API_ErrorCheckinExists {
            get {
                return ResourceManager.GetString("API_ErrorCheckinExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session token.
        /// </summary>
        public static string API_ErrorInvalidToken {
            get {
                return ResourceManager.GetString("API_ErrorInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Badly Defined.
        /// </summary>
        public static string API_ErrorMethodDefinition {
            get {
                return ResourceManager.GetString("API_ErrorMethodDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have any role assigned.
        /// </summary>
        public static string API_ErrorNoRolesAssigned {
            get {
                return ResourceManager.GetString("API_ErrorNoRolesAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have enough privileges to access this resource..
        /// </summary>
        public static string API_ErrorSessionPrivilegesRequired {
            get {
                return ResourceManager.GetString("API_ErrorSessionPrivilegesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You require an active session to access that resource..
        /// </summary>
        public static string API_ErrorSessionRequired {
            get {
                return ResourceManager.GetString("API_ErrorSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The space is already in use.
        /// </summary>
        public static string API_ErrorSpaceUsed {
            get {
                return ResourceManager.GetString("API_ErrorSpaceUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Buttons_Cancel {
            get {
                return ResourceManager.GetString("Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin.
        /// </summary>
        public static string Buttons_Checkin {
            get {
                return ResourceManager.GetString("Buttons_Checkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Buttons_Checkout {
            get {
                return ResourceManager.GetString("Buttons_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Buttons_Confirm {
            get {
                return ResourceManager.GetString("Buttons_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Buttons_Save {
            get {
                return ResourceManager.GetString("Buttons_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Buttons_SendMessage {
            get {
                return ResourceManager.GetString("Buttons_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify and Leave!.
        /// </summary>
        public static string Dashboard_ActionBtn_Blocked {
            get {
                return ResourceManager.GetString("Dashboard_ActionBtn_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to leave!.
        /// </summary>
        public static string Dashboard_ActionBtn_Normal {
            get {
                return ResourceManager.GetString("Dashboard_ActionBtn_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Footer_About {
            get {
                return ResourceManager.GetString("Footer_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Footer_Help {
            get {
                return ResourceManager.GetString("Footer_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Footer_Home {
            get {
                return ResourceManager.GetString("Footer_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Footer_Login {
            get {
                return ResourceManager.GetString("Footer_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Footer_Privacy {
            get {
                return ResourceManager.GetString("Footer_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sieena.
        /// </summary>
        public static string Footer_Sieena {
            get {
                return ResourceManager.GetString("Footer_Sieena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Footer_Terms {
            get {
                return ResourceManager.GetString("Footer_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Header_Login {
            get {
                return ResourceManager.GetString("Header_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Header_Logout {
            get {
                return ResourceManager.GetString("Header_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string Header_Profile {
            get {
                return ResourceManager.GetString("Header_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome .
        /// </summary>
        public static string Header_WelcomeText {
            get {
                return ResourceManager.GetString("Header_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading current checkins....
        /// </summary>
        public static string Loader_Checkins {
            get {
                return ResourceManager.GetString("Loader_Checkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Spaces....
        /// </summary>
        public static string Loader_Spaces {
            get {
                return ResourceManager.GetString("Loader_Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Users....
        /// </summary>
        public static string Loader_Users {
            get {
                return ResourceManager.GetString("Loader_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        public static string Login_AfterSubmit {
            get {
                return ResourceManager.GetString("Login_AfterSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string Login_ErrorValidation {
            get {
                return ResourceManager.GetString("Login_ErrorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login_Submit {
            get {
                return ResourceManager.GetString("Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to check-in in spot: &lt;strong&gt;{{Alias}}&lt;/strong&gt;.
        /// </summary>
        public static string Main_ConfirmCheckinMessage {
            get {
                return ResourceManager.GetString("Main_ConfirmCheckinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Checkin.
        /// </summary>
        public static string Main_ConfirmCheckinTitle {
            get {
                return ResourceManager.GetString("Main_ConfirmCheckinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space not available!.
        /// </summary>
        public static string Main_ErrorSpaceNotAvailable {
            get {
                return ResourceManager.GetString("Main_ErrorSpaceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already checked in.
        /// </summary>
        public static string Main_InfoAlreadyCheckedIn {
            get {
                return ResourceManager.GetString("Main_InfoAlreadyCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        public static string Membership_AppId {
            get {
                return ResourceManager.GetString("Membership_AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not implemented.
        /// </summary>
        public static string Membership_NotImplemented {
            get {
                return ResourceManager.GetString("Membership_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Notification_AlertTitle {
            get {
                return ResourceManager.GetString("Notification_AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is looking for you, he/she needs you to move your car. Thanks! \n MyPlace.
        /// </summary>
        public static string Notification_EmailMessage {
            get {
                return ResourceManager.GetString("Notification_EmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [MyPlace] Someone needs you to move your car!.
        /// </summary>
        public static string Notification_EmailTitle {
            get {
                return ResourceManager.GetString("Notification_EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, {0} is looking for you, he/she needs you to move your car. :).
        /// </summary>
        public static string Notification_IMMessage {
            get {
                return ResourceManager.GetString("Notification_IMMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is leaving, please move your car..
        /// </summary>
        public static string Notification_SomeoneLeaving {
            get {
                return ResourceManager.GetString("Notification_SomeoneLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a space available!.
        /// </summary>
        public static string Notification_SpaceAvailable {
            get {
                return ResourceManager.GetString("Notification_SpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Notification_WindowTitle {
            get {
                return ResourceManager.GetString("Notification_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellphone.
        /// </summary>
        public static string Profile_Cellphone {
            get {
                return ResourceManager.GetString("Profile_Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSN Email.
        /// </summary>
        public static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Profile_Locale {
            get {
                return ResourceManager.GetString("Profile_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to receive an alert when a place becomes &lt;span class=&quot;available&quot;&gt;available&lt;/span&gt;.
        /// </summary>
        public static string Profile_Notifications_Availability {
            get {
                return ResourceManager.GetString("Profile_Notifications_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification settings saved successfully.
        /// </summary>
        public static string Profile_Notifications_Success {
            get {
                return ResourceManager.GetString("Profile_Notifications_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to suscribe to some of these &lt;span class=&quot;bold&quot;&gt;notifications&lt;/span&gt;?.
        /// </summary>
        public static string Profile_Notifications_Title {
            get {
                return ResourceManager.GetString("Profile_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated correctly.
        /// </summary>
        public static string Profile_Success {
            get {
                return ResourceManager.GetString("Profile_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Profile_TabNotifications {
            get {
                return ResourceManager.GetString("Profile_TabNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string TEST {
            get {
                return ResourceManager.GetString("TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string TimeAgo_Days {
            get {
                return ResourceManager.GetString("TimeAgo_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        public static string TimeAgo_Hour {
            get {
                return ResourceManager.GetString("TimeAgo_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string TimeAgo_Hours {
            get {
                return ResourceManager.GetString("TimeAgo_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string TimeAgo_JustNow {
            get {
                return ResourceManager.GetString("TimeAgo_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute ago.
        /// </summary>
        public static string TimeAgo_Minute {
            get {
                return ResourceManager.GetString("TimeAgo_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string TimeAgo_Minutes {
            get {
                return ResourceManager.GetString("TimeAgo_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks ago.
        /// </summary>
        public static string TimeAgo_Weeks {
            get {
                return ResourceManager.GetString("TimeAgo_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string TimeAgo_Yesterday {
            get {
                return ResourceManager.GetString("TimeAgo_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived at.
        /// </summary>
        public static string UserInfo_ArrivalTime {
            get {
                return ResourceManager.GetString("UserInfo_ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserInfo_ContactEmail {
            get {
                return ResourceManager.GetString("UserInfo_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellphone.
        /// </summary>
        public static string UserInfo_PhoneCel {
            get {
                return ResourceManager.GetString("UserInfo_PhoneCel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No..
        /// </summary>
        public static string UserInfo_PhoneOffice {
            get {
                return ResourceManager.GetString("UserInfo_PhoneOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        public static string UserInfo_PhoneOfficeExtension {
            get {
                return ResourceManager.GetString("UserInfo_PhoneOfficeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name to filter down the list....
        /// </summary>
        public static string UserSelector_FilterText {
            get {
                return ResourceManager.GetString("UserSelector_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User.
        /// </summary>
        public static string UserSelector_Title {
            get {
                return ResourceManager.GetString("UserSelector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Word_Hi {
            get {
                return ResourceManager.GetString("Word_Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string Word_Thanks {
            get {
                return ResourceManager.GetString("Word_Thanks", resourceCulture);
            }
        }
    }
}
