ALTER TABLE [dbo].[Roles]
    ADD CONSTRAINT [IX_Roles] UNIQUE NONCLUSTERED ([RoleLevel] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

