ALTER TABLE [dbo].[Checkins]
    ADD CONSTRAINT [PK_Checkins] PRIMARY KEY CLUSTERED ([CheckInId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

