ALTER TABLE [dbo].[Endpoints]
    ADD CONSTRAINT [PK_EndpointTypes] PRIMARY KEY CLUSTERED ([EndpointTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

