ALTER TABLE [dbo].[OAuthTokens]
    ADD CONSTRAINT [PK_OAuthTokens] PRIMARY KEY CLUSTERED ([UserId] ASC, [ProviderId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

