ALTER TABLE [dbo].[SpaceBlockings]
    ADD CONSTRAINT [PK_SpaceBlockings] PRIMARY KEY CLUSTERED ([BaseSpaceId] ASC, [BlockingSpaceId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

