ALTER TABLE [dbo].[SpaceLocations]
    ADD CONSTRAINT [PK_SpaceLocations] PRIMARY KEY CLUSTERED ([SpaceId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

