ALTER TABLE [dbo].[UserEndpoints]
    ADD CONSTRAINT [PK_UserEndpoints] PRIMARY KEY CLUSTERED ([UserId] ASC, [EndpointTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

